parameters:
    jwt_secret: '%env(JWT_PASSPHRASE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Security\JwtAuthenticator:
        arguments:
            $jwtSecretKey: '%jwt_secret%'
